# Services descriptions for Miele

process_action:
  name: Execute process action
  description: Executes process action if preconditions are met.

  fields:
    device_id:
      name: Target device
      description: "Select the device to control"
      required: true
      example: "abcdef12345"
      selector:
        device:
          integration: "miele"
    action:
      # Field name as shown in UI
      name: Action
      description: Select desired processAction command
      required: true
      advanced: false
      # Example value that can be passed for this field
      example: "start"
      # The default field value
      default: ""
      selector:
        select:
          options:
            - value: "start"
              label: "Start"
            - value: "stop"
              label: "Stop"
            - value: "pause"
              label: "Pause"
            - value: "start_superfreezing"
              label: "Start superfreezing"
            - value: "stop_superfreezing"
              label: "Stop superfreezing"
            - value: "start_supercooling"
              label: "Start supercooling"
            - value: "stop_supercooling"
              label: "Stop supercooling"

modes_action:
  name: Execute set mode action
  description: Executes set mode action if preconditions are met.

  fields:
    device_id:
      name: Target device
      description: "Select the device to control"
      required: true
      example: "abcdef12345"
      selector:
        device:
          integration: "miele"
    mode:
      # Field name as shown in UI
      name: Mode
      description: Select desired modes command
      required: true
      advanced: false
      example: 0
      selector:
        select:
          options:
            - value: "mode_normal"
              label: "Normal mode"
            - value: "mode_sabbath"
              label: "Sabbath mode"
            - value: "mode_party"
              label: "Party mode"
            - value: "mode_holiday"
              label: "Holiday mode"

generic_action:
  name: Execute generic action
  description: Executes one action on a device
  target:
    device:
      integration: "miele"
  fields:
    processAction:
      example: 1
      description: Set processAction
    light:
      description: Set light on or off
      example: 1
    startTime:
      description: Set start time
      example: "[1, 30]"
    ventilationStep:
      description: Select ventilation step
      example: 1
    programId:
      description: Set program
      example: 24
    targetTemperature:
      description: Set target temperature
      example: '[{ "zone": 1, "value": 5 }]'
    deviceName:
      description: Rename device
      example: "A new name"
    powerOn:
      description: Power on appliance
      example: true
    powerOff:
      description: Power off appliance
      example: true
    colors:
      example: "blue"
      description: Set color of ambient light
    modes:
      description: Set mode
      example: 1

raw:
  name: Execute raw action
  description: Execute service with minmal validation.
  fields:
    serialno:
      description: The serial number of the appliance
      example: "123456"
    extra:
      description: A dictionary with parameters
      example: '{ "targetTemperature": [{"zone": 1, "value": -18 }] }'

set_program:
  name: Set program
  description: Set and start program with optional parameters.
  target:
    device:
      integration: "miele"
  fields:
    programId:
      description: Set program Id
      example: 24

